/** SOLE owner of React Query keys. Admin keys are tenant(store)-scoped. */
export const queryKeys = {
    admin: {
        me: () => ["admin", "me"] as const,
        compare: (days: number) => ["admin", "compare", days] as const,
        summary: (store: string, days: number) => ["admin", store, "summary", days] as const,
        experiments: (store: string, days: number) => ["admin", store, "experiments", days] as const,
        orders: (store: string, params: Record<string, string | number>) => ["admin", store, "orders", params] as const,
        order: (store: string, id: string) => ["admin", store, "order", id] as const,
        customers: (store: string, params: Record<string, string | number>) => ["admin", store, "customers", params] as const,
        customer: (store: string, email: string) => ["admin", store, "customer", email] as const,
        segments: (store: string) => ["admin", store, "segments"] as const,
        segmentPreview: (store: string, rules: object) => ["admin", store, "segments", "preview", rules] as const,
        products: (store: string) => ["admin", store, "products"] as const,
        catalogSchema: (store: string) => ["admin", store, "catalog-schema"] as const,
        returns: (store: string, status: string) => ["admin", store, "returns", status] as const,
        reviews: (store: string, status: string) => ["admin", store, "reviews", status] as const,
        pages: (store: string) => ["admin", store, "pages"] as const,
        sectionLibrary: (store: string) => ["admin", store, "section-library"] as const,
        posts: (store: string) => ["admin", store, "posts"] as const,
        theme: (store: string) => ["admin", store, "theme"] as const,
        bookings: (store: string, from: string) => ["admin", store, "bookings", from] as const,
        services: (store: string) => ["admin", store, "services"] as const,
        staff: (store: string) => ["admin", store, "staff"] as const,
        closures: (store: string) => ["admin", store, "closures"] as const,
        memberships: (store: string) => ["admin", store, "memberships"] as const,
        audit: (store: string, outcome = "all", limit = 100) => ["admin", store, "audit", outcome, limit] as const,
    },
    store: {
        session: (store: string) => ["store", store, "session"] as const,
        me: (store: string) => ["store", store, "me"] as const,
        orders: (store: string) => ["store", store, "orders"] as const,
        bookings: (store: string) => ["store", store, "bookings"] as const,
        bookingServices: (store: string) => ["store", store, "booking-services"] as const,
        availability: (store: string, service: string, date: string, staff: string) => ["store", store, "availability", service, date, staff] as const,
        checkoutStatus: (store: string, id: string) => ["store", store, "checkout-status", id] as const,
    },
} as const;
